// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace BankaProjekat.Migrations
{
    [DbContext(typeof(BankaContext))]
    partial class BankaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("JMBG")
                        .HasColumnType("bigint");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Models.Nalog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool?>("admin")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("korisnikID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("korisnikID");

                    b.ToTable("Nalog");
                });

            modelBuilder.Entity("Models.Racun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Broj")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DatumOtvaranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZatvaranja")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Stanje")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("Valuta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("korisnikID")
                        .HasColumnType("int");

                    b.Property<int?>("vrstaRacunaid")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("korisnikID");

                    b.HasIndex("vrstaRacunaid");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("Models.VrsteRacuna", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("VrsteRacunaid")
                        .HasColumnType("int");

                    b.Property<string>("vrstaNaziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("VrsteRacunaid");

                    b.ToTable("VrsteRacuna");
                });

            modelBuilder.Entity("Models.Nalog", b =>
                {
                    b.HasOne("Models.Korisnik", "korisnik")
                        .WithMany()
                        .HasForeignKey("korisnikID");

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("Models.Racun", b =>
                {
                    b.HasOne("Models.Korisnik", "korisnik")
                        .WithMany("Racuni")
                        .HasForeignKey("korisnikID");

                    b.HasOne("Models.VrsteRacuna", "vrstaRacuna")
                        .WithMany()
                        .HasForeignKey("vrstaRacunaid");

                    b.Navigation("korisnik");

                    b.Navigation("vrstaRacuna");
                });

            modelBuilder.Entity("Models.VrsteRacuna", b =>
                {
                    b.HasOne("Models.VrsteRacuna", null)
                        .WithMany("racuni")
                        .HasForeignKey("VrsteRacunaid");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Navigation("Racuni");
                });

            modelBuilder.Entity("Models.VrsteRacuna", b =>
                {
                    b.Navigation("racuni");
                });
#pragma warning restore 612, 618
        }
    }
}
